; Inspired from https://github.com/Jason2866/Tasmota-build
[platformio]
description = LGFX_PPA build test
src_dir = main

[coding_standards]
build_flags       =
    -Wno-unused-variable
    -Wno-unused-but-set-variable
    -Wno-sign-compare
    -Wunreachable-code
    -Wall
    -Wextra
    -Wshadow
    -Wdouble-promotion
    -Wformat
    -Wnonnull

[env]
framework = arduino
lib_deps = LGFX_PPA

[platform_default]
platformio        = platform-espressif32
pioarduino        = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip

[espressif32_latest]
platform          = ${platform_default.pioarduino}
build_flags       = ${coding_standards.build_flags}

[M5Stack_tab5]
board = esp32-p4-evboard
board_build.mcu = esp32p4
board_build.flash_mode = qio
;--flash-freq 80m
board_build.flash_freq = 80m
; PartitionScheme=app3M_fat9M_16MB
board_build.partitions = app3M_fat9M_16MB.csv
board_build.f_cpu = 360000000L
; esp32p4.build.img_freq = 80m
board_build.img_freq = 40m
build_flags =
  ${env.build_flags}
  -DARDUINO_M5STACK_TAB5


[env:m5stack-m5gfx]
extends          = M5Stack_tab5, espressif32_latest
lib_deps =
  ${env.lib_deps}
  M5GFX
  M5Unified
build_flags =
  ${env.build_flags}
  -DCONFIG_LGFX_PPA_USE_M5GFX

[env:m5stack-lgfx]
extends          = M5Stack_tab5, espressif32_latest
lib_deps =
  ${env.lib_deps}
  LovyanGFX
build_flags =
  ${env.build_flags}
  -DCONFIG_LGFX_PPA_USE_LGFX
